import { ModuleViewer } from '@/components/learning/ModuleViewer'
import { auth } from '@/auth'
import { notFound } from 'next/navigation'

// Demo module data - in production this would come from database
const demoModules: Record<string, any> = {
  'carbon-footprint': {
    id: 'mod-carbon-1',
    title: 'Understanding Your Carbon Footprint',
    slug: 'carbon-footprint',
    description: 'Learn how to measure, track, and reduce your personal environmental impact with practical tools and strategies.',
    category: 'FUNDAMENTALS',
    duration: 45,
    color: 'moss',
    lessons: [
      {
        id: 'les-cf-1',
        title: 'What is a Carbon Footprint?',
        order: 1,
        content: `
          <h3>Definition & Overview</h3>
          <p>A <strong>carbon footprint</strong> is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. It's measured in tons of CO2 equivalent per year.</p>

          <h3>Why It Matters</h3>
          <p>Understanding your carbon footprint is the first step toward reducing your environmental impact. The average American has a carbon footprint of about <strong>16 tons per year</strong> - one of the highest in the world. The global average is closer to 4 tons.</p>

          <h3>Key Sources of Carbon Emissions</h3>
          <ul>
            <li><strong>Transportation</strong> - Cars, flights, and public transit</li>
            <li><strong>Home Energy</strong> - Heating, cooling, and electricity</li>
            <li><strong>Food</strong> - Production, transportation, and waste</li>
            <li><strong>Goods & Services</strong> - Manufacturing and shipping</li>
          </ul>

          <blockquote>
            "The greatest threat to our planet is the belief that someone else will save it." - Robert Swan
          </blockquote>
        `
      },
      {
        id: 'les-cf-2',
        title: 'Measuring Your Impact',
        order: 2,
        content: `
          <h3>Carbon Footprint Calculators</h3>
          <p>Several tools can help you measure your personal carbon footprint:</p>

          <ul>
            <li><strong>EPA Carbon Calculator</strong> - Official US government tool</li>
            <li><strong>Carbon Footprint Ltd</strong> - Comprehensive international calculator</li>
            <li><strong>Project Exodus Calculator</strong> - Our own tool (coming soon!)</li>
          </ul>

          <h3>What to Track</h3>
          <p>When calculating your footprint, you'll need to gather information about:</p>

          <ol>
            <li><strong>Home energy usage</strong> - Check your utility bills for electricity and gas consumption</li>
            <li><strong>Transportation habits</strong> - Miles driven, flights taken, public transit use</li>
            <li><strong>Diet choices</strong> - Meat consumption, food waste, local vs. imported foods</li>
            <li><strong>Shopping habits</strong> - New purchases, secondhand items, product origins</li>
          </ol>

          <h3>Setting a Baseline</h3>
          <p>Calculate your current footprint to establish a baseline. This gives you a starting point to measure progress against as you implement changes.</p>
        `
      },
      {
        id: 'les-cf-3',
        title: 'Reduction Strategies',
        order: 3,
        content: `
          <h3>High-Impact Actions</h3>
          <p>Research shows these actions have the biggest impact on reducing your carbon footprint:</p>

          <h4>1. Transportation (Biggest Impact)</h4>
          <ul>
            <li>Live car-free: saves 2.4 tons CO2/year</li>
            <li>Avoid one transatlantic flight: saves 1.6 tons CO2</li>
            <li>Switch to electric vehicle: saves 2.5 tons CO2/year</li>
          </ul>

          <h4>2. Home Energy</h4>
          <ul>
            <li>Switch to renewable energy: saves 1.5 tons CO2/year</li>
            <li>Improve insulation: saves 0.5-1 ton CO2/year</li>
            <li>Use LED lighting: saves 0.1 ton CO2/year</li>
          </ul>

          <h4>3. Diet</h4>
          <ul>
            <li>Plant-based diet: saves 0.8 tons CO2/year</li>
            <li>Reduce food waste: saves 0.3 tons CO2/year</li>
            <li>Buy local and seasonal: variable but significant</li>
          </ul>

          <h3>Creating Your Action Plan</h3>
          <p>Start with one or two changes and build from there. Small, consistent actions add up to significant impact over time.</p>
        `
      },
      {
        id: 'les-cf-4',
        title: 'Tracking Progress',
        order: 4,
        content: `
          <h3>Building Sustainable Habits</h3>
          <p>Reducing your carbon footprint isn't a one-time action - it's an ongoing journey. Here's how to stay on track:</p>

          <h4>Monthly Check-ins</h4>
          <ul>
            <li>Review your utility bills</li>
            <li>Track transportation miles</li>
            <li>Assess food waste reduction</li>
            <li>Celebrate wins and adjust strategies</li>
          </ul>

          <h4>Annual Assessment</h4>
          <p>Recalculate your full carbon footprint annually to see how far you've come. Compare against your baseline and set new goals.</p>

          <h3>Beyond Individual Action</h3>
          <p>While personal changes matter, systemic change is also crucial:</p>
          <ul>
            <li>Advocate for climate policies</li>
            <li>Support sustainable businesses</li>
            <li>Engage your community</li>
            <li>Vote for environmental protection</li>
          </ul>

          <h3>Remember</h3>
          <p>Progress, not perfection. Every reduction in emissions matters. You're part of a global movement working toward a sustainable future.</p>
        `
      }
    ],
    quiz: {
      id: 'quiz-cf-1',
      passingScore: 80,
      questions: [
        {
          id: 'q-cf-1',
          question: 'What is the average carbon footprint of an American per year?',
          explanation: 'Americans have one of the highest per-capita carbon footprints in the world at approximately 16 tons of CO2 per year, compared to the global average of about 4 tons.',
          options: [
            { id: 'q1-a', text: '4 tons', isCorrect: false },
            { id: 'q1-b', text: '8 tons', isCorrect: false },
            { id: 'q1-c', text: '16 tons', isCorrect: true },
            { id: 'q1-d', text: '24 tons', isCorrect: false }
          ]
        },
        {
          id: 'q-cf-2',
          question: 'Which action typically has the BIGGEST impact on reducing personal carbon emissions?',
          explanation: 'Living car-free or avoiding air travel has the biggest impact. A single transatlantic flight can add 1.6 tons of CO2, and going car-free saves about 2.4 tons per year.',
          options: [
            { id: 'q2-a', text: 'Using LED light bulbs', isCorrect: false },
            { id: 'q2-b', text: 'Living car-free or reducing flights', isCorrect: true },
            { id: 'q2-c', text: 'Recycling paper products', isCorrect: false },
            { id: 'q2-d', text: 'Turning off lights when leaving a room', isCorrect: false }
          ]
        },
        {
          id: 'q-cf-3',
          question: 'What are the main sources of personal carbon emissions?',
          explanation: 'The main sources are transportation, home energy use, food choices, and purchased goods/services. Transportation is typically the largest source for most Americans.',
          options: [
            { id: 'q3-a', text: 'Only electricity use', isCorrect: false },
            { id: 'q3-b', text: 'Transportation, home energy, food, and goods', isCorrect: true },
            { id: 'q3-c', text: 'Only driving and flying', isCorrect: false },
            { id: 'q3-d', text: 'Only food production', isCorrect: false }
          ]
        },
        {
          id: 'q-cf-4',
          question: 'How much CO2 can switching to a plant-based diet save annually?',
          explanation: 'Adopting a plant-based diet can save approximately 0.8 tons of CO2 per year, making it one of the more impactful dietary changes.',
          options: [
            { id: 'q4-a', text: '0.1 tons', isCorrect: false },
            { id: 'q4-b', text: '0.8 tons', isCorrect: true },
            { id: 'q4-c', text: '5 tons', isCorrect: false },
            { id: 'q4-d', text: '10 tons', isCorrect: false }
          ]
        },
        {
          id: 'q-cf-5',
          question: 'Why is it important to establish a baseline carbon footprint?',
          explanation: 'A baseline gives you a starting point to measure your progress against. Without knowing where you started, you can\'t accurately track how much you\'ve reduced your impact.',
          options: [
            { id: 'q5-a', text: 'It\'s required by law', isCorrect: false },
            { id: 'q5-b', text: 'To compare with celebrities', isCorrect: false },
            { id: 'q5-c', text: 'To measure progress and track reductions', isCorrect: true },
            { id: 'q5-d', text: 'It\'s only useful for businesses', isCorrect: false }
          ]
        }
      ]
    }
  },
  'water-conservation': {
    id: 'mod-water-1',
    title: 'The Water Cycle & Conservation',
    slug: 'water-conservation',
    description: 'Explore how water systems work and discover innovative techniques for conservation at home and in your community.',
    category: 'WATER SYSTEMS',
    duration: 60,
    color: 'ocean',
    lessons: [
      {
        id: 'les-wc-1',
        title: 'Understanding the Water Cycle',
        order: 1,
        content: `
          <h3>The Natural Water Cycle</h3>
          <p>Water is constantly moving through our planet in a continuous cycle of evaporation, condensation, precipitation, and collection.</p>

          <h4>Key Stages</h4>
          <ul>
            <li><strong>Evaporation</strong> - Sun heats water in oceans, lakes, and rivers, turning it into vapor</li>
            <li><strong>Condensation</strong> - Water vapor cools and forms clouds</li>
            <li><strong>Precipitation</strong> - Water falls as rain, snow, sleet, or hail</li>
            <li><strong>Collection</strong> - Water gathers in oceans, lakes, rivers, and groundwater</li>
          </ul>

          <h3>Human Impact on the Water Cycle</h3>
          <p>Human activities have significantly altered the natural water cycle through:</p>
          <ul>
            <li>Dam construction changing river flows</li>
            <li>Groundwater pumping depleting aquifers</li>
            <li>Climate change affecting precipitation patterns</li>
            <li>Urban development increasing runoff</li>
          </ul>
        `
      },
      {
        id: 'les-wc-2',
        title: 'Water Scarcity & Global Challenges',
        order: 2,
        content: `
          <h3>The Global Water Crisis</h3>
          <p>Despite Earth being 70% water, only <strong>3% is freshwater</strong>, and less than 1% is readily accessible for human use.</p>

          <h4>Alarming Statistics</h4>
          <ul>
            <li>2.2 billion people lack access to safe drinking water</li>
            <li>Half the world's population could live in water-stressed areas by 2025</li>
            <li>Agriculture uses 70% of global freshwater withdrawals</li>
            <li>Water demand is projected to increase 55% by 2050</li>
          </ul>

          <h3>Causes of Water Scarcity</h3>
          <ol>
            <li><strong>Climate Change</strong> - Altered rainfall patterns and increased evaporation</li>
            <li><strong>Population Growth</strong> - More people requiring more water</li>
            <li><strong>Pollution</strong> - Contaminating available freshwater sources</li>
            <li><strong>Inefficient Use</strong> - Wasting water in agriculture and industry</li>
          </ol>
        `
      },
      {
        id: 'les-wc-3',
        title: 'Home Water Conservation',
        order: 3,
        content: `
          <h3>Indoor Water Saving Tips</h3>

          <h4>Bathroom (Biggest Indoor Water Use)</h4>
          <ul>
            <li>Install low-flow showerheads (saves 2.5 gallons/minute)</li>
            <li>Fix leaky faucets (can waste 3,000 gallons/year)</li>
            <li>Use dual-flush toilets (saves up to 4,000 gallons/year)</li>
            <li>Take shorter showers (5 minutes saves 10-25 gallons)</li>
          </ul>

          <h4>Kitchen</h4>
          <ul>
            <li>Run dishwasher only when full</li>
            <li>Install aerators on faucets</li>
            <li>Compost instead of using garbage disposal</li>
            <li>Keep drinking water in the fridge instead of running tap</li>
          </ul>

          <h4>Laundry</h4>
          <ul>
            <li>Wash full loads only</li>
            <li>Use high-efficiency washing machines</li>
            <li>Adjust water level to load size</li>
          </ul>

          <h3>Outdoor Conservation</h3>
          <ul>
            <li>Water lawns early morning or evening</li>
            <li>Use drip irrigation instead of sprinklers</li>
            <li>Plant native, drought-resistant plants</li>
            <li>Collect rainwater for garden use</li>
          </ul>
        `
      },
      {
        id: 'les-wc-4',
        title: 'Rainwater Harvesting',
        order: 4,
        content: `
          <h3>What is Rainwater Harvesting?</h3>
          <p>Rainwater harvesting is the collection and storage of rainwater for later use. It's an ancient practice that's becoming increasingly important in modern sustainable living.</p>

          <h4>Benefits</h4>
          <ul>
            <li>Reduces water bills</li>
            <li>Decreases stormwater runoff</li>
            <li>Provides water during droughts</li>
            <li>Reduces demand on municipal systems</li>
          </ul>

          <h3>Basic Rainwater Harvesting System</h3>
          <ol>
            <li><strong>Catchment Area</strong> - Usually your roof</li>
            <li><strong>Gutters & Downspouts</strong> - Channel water to storage</li>
            <li><strong>First Flush Diverter</strong> - Removes initial dirty water</li>
            <li><strong>Storage Tank</strong> - Holds collected water</li>
            <li><strong>Distribution System</strong> - Pipes or hoses for use</li>
          </ol>

          <h3>Getting Started</h3>
          <p>A simple rain barrel connected to your downspout is an easy first step. A 1-inch rainfall on a 1,000 sq ft roof yields about 600 gallons of water!</p>
        `
      }
    ],
    quiz: {
      id: 'quiz-wc-1',
      passingScore: 80,
      questions: [
        {
          id: 'q-wc-1',
          question: 'What percentage of Earth\'s water is freshwater?',
          explanation: 'Although Earth is 70% water, only about 3% is freshwater, and less than 1% is readily accessible for human use.',
          options: [
            { id: 'qw1-a', text: '97%', isCorrect: false },
            { id: 'qw1-b', text: '50%', isCorrect: false },
            { id: 'qw1-c', text: '3%', isCorrect: true },
            { id: 'qw1-d', text: '25%', isCorrect: false }
          ]
        },
        {
          id: 'q-wc-2',
          question: 'Which sector uses the most freshwater globally?',
          explanation: 'Agriculture accounts for approximately 70% of global freshwater withdrawals, primarily for irrigation.',
          options: [
            { id: 'qw2-a', text: 'Residential households', isCorrect: false },
            { id: 'qw2-b', text: 'Agriculture', isCorrect: true },
            { id: 'qw2-c', text: 'Manufacturing', isCorrect: false },
            { id: 'qw2-d', text: 'Energy production', isCorrect: false }
          ]
        },
        {
          id: 'q-wc-3',
          question: 'How much water can a leaky faucet waste per year?',
          explanation: 'A leaky faucet dripping at one drop per second can waste over 3,000 gallons of water per year.',
          options: [
            { id: 'qw3-a', text: '100 gallons', isCorrect: false },
            { id: 'qw3-b', text: '500 gallons', isCorrect: false },
            { id: 'qw3-c', text: '3,000 gallons', isCorrect: true },
            { id: 'qw3-d', text: '50 gallons', isCorrect: false }
          ]
        },
        {
          id: 'q-wc-4',
          question: 'What is the best time to water your lawn to minimize evaporation?',
          explanation: 'Watering early morning or evening when temperatures are cooler reduces evaporation and ensures more water reaches plant roots.',
          options: [
            { id: 'qw4-a', text: 'Midday when it\'s warmest', isCorrect: false },
            { id: 'qw4-b', text: 'Early morning or evening', isCorrect: true },
            { id: 'qw4-c', text: 'Anytime during the day', isCorrect: false },
            { id: 'qw4-d', text: 'Only at night', isCorrect: false }
          ]
        },
        {
          id: 'q-wc-5',
          question: 'How much water can be collected from 1 inch of rain on a 1,000 sq ft roof?',
          explanation: 'A 1-inch rainfall on a 1,000 square foot roof can yield approximately 600 gallons of water - a significant amount for garden use!',
          options: [
            { id: 'qw5-a', text: '100 gallons', isCorrect: false },
            { id: 'qw5-b', text: '300 gallons', isCorrect: false },
            { id: 'qw5-c', text: '600 gallons', isCorrect: true },
            { id: 'qw5-d', text: '1,000 gallons', isCorrect: false }
          ]
        }
      ]
    }
  }
}

async function getModule(slug: string) {
  // In production, fetch from database
  // const module = await prisma.learningModule.findUnique({
  //   where: { slug },
  //   include: {
  //     lessons: { orderBy: { order: 'asc' } },
  //     quiz: {
  //       include: {
  //         questions: {
  //           include: { options: true },
  //           orderBy: { order: 'asc' }
  //         }
  //       }
  //     }
  //   }
  // })

  return demoModules[slug] || null
}

async function getUserProgress(userId: string, moduleId: string) {
  // In production, fetch from database
  // const progress = await prisma.userModuleProgress.findUnique({
  //   where: { userId_moduleId: { userId, moduleId } }
  // })
  return null
}

export default async function ModulePage({
  params
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params
  const module = await getModule(slug)

  if (!module) {
    notFound()
  }

  const session = await auth()
  const userId = session?.user?.id

  let progress = null
  if (userId) {
    progress = await getUserProgress(userId, module.id)
  }

  return (
    <ModuleViewer
      module={module}
      userId={userId}
      initialProgress={progress}
    />
  )
}
