import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/auth'
import { CONTENT_LIMITS } from '@/lib/article/contentSecurity'
import { reflowExtractedText } from '@/lib/article/reflowText'
import { PDFParse } from 'pdf-parse'

export const runtime = 'nodejs'
export const maxDuration = 120 // 2 minutes for large PDFs

export async function POST(request: NextRequest) {
  let parser: PDFParse | null = null

  try {
    const session = await auth()
    if (!session?.user?.id) {
      return NextResponse.json(
        { success: false, error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const formData = await request.formData()
    const file = formData.get('pdf') as File | null

    if (!file) {
      return NextResponse.json(
        { success: false, error: 'No PDF file provided' },
        { status: 400 }
      )
    }

    // Validate file type
    if (!file.name.toLowerCase().endsWith('.pdf')) {
      return NextResponse.json(
        { success: false, error: 'File must be a PDF' },
        { status: 400 }
      )
    }

    // Validate file size
    if (file.size > CONTENT_LIMITS.MAX_PDF_FILE_SIZE) {
      return NextResponse.json(
        { success: false, error: `PDF is too large (max ${CONTENT_LIMITS.MAX_PDF_FILE_SIZE / (1024 * 1024)}MB)` },
        { status: 400 }
      )
    }

    // Read file into buffer
    const arrayBuffer = await file.arrayBuffer()
    const buffer = Buffer.from(arrayBuffer)

    // Validate PDF magic bytes (%PDF-)
    if (buffer.length < 5 || buffer.subarray(0, 5).toString('ascii') !== '%PDF-') {
      return NextResponse.json(
        { success: false, error: 'File does not appear to be a valid PDF' },
        { status: 400 }
      )
    }

    // Parse PDF using pdf-parse v2 API
    parser = new PDFParse({ data: buffer })

    // Two-pass extraction:
    //   1. Aggressive line-detection settings — best for traditional
    //      PDFs (Word, Acrobat, LaTeX) where text flows in obvious lines.
    //   2. Fallback to defaults — better for PDFs generated by Chrome's
    //      "Print to PDF" / "Save as PDF" feature and other web-rendered
    //      PDFs, which often have non-linear text positioning that
    //      defeats aggressive line detection.
    let textResult = await parser.getText({
      lineEnforce: true,
      lineThreshold: 4.6,
      pageJoiner: '\n\n',
    })
    let text = textResult.text || ''
    let extractionMode = 'lineEnforce'

    if (!text.trim()) {
      textResult = await parser.getText({ pageJoiner: '\n\n' })
      text = textResult.text || ''
      extractionMode = 'default'
    }

    if (!text.trim()) {
      textResult = await parser.getText()
      text = textResult.text || ''
      extractionMode = 'raw'
    }

    const numPages = textResult.total || 0

    if (!text.trim()) {
      return NextResponse.json(
        { success: false, error: 'Could not extract text from this PDF. It looks like an image-only / scanned PDF — try copying the text you want to use and pasting it directly instead.' },
        { status: 400 }
      )
    }

    // Reflow: merge wrapped lines within a paragraph back into one
    // paragraph and handle end-of-line hyphenation. Without this,
    // every visual line in the PDF becomes its own <p> in the editor.
    text = reflowExtractedText(text)

    // Log when we had to fall back so we can see in Vercel logs which
    // PDFs are hitting the alternate paths.
    if (extractionMode !== 'lineEnforce') {
      console.log(`[parse-pdf] Used fallback extraction (${extractionMode}) for ${file.name}`)
    }

    // Get metadata if available — sanitize string values to prevent XSS
    const info: Record<string, string> = {}
    try {
      const infoResult = await parser.getInfo()
      const rawInfo = infoResult.info || {}
      // Only extract known safe string fields, strip any HTML
      const safeFields = ['Title', 'Author', 'Subject', 'Creator', 'Producer']
      for (const field of safeFields) {
        if (rawInfo[field] && typeof rawInfo[field] === 'string') {
          info[field] = rawInfo[field].replace(/<[^>]*>/g, '').slice(0, 500)
        }
      }
    } catch {
      // Info extraction is optional
    }

    return NextResponse.json({
      success: true,
      data: {
        text,
        numPages,
        info,
      },
    })
  } catch (error) {
    console.error('PDF parse error:', error)
    return NextResponse.json(
      { success: false, error: 'Failed to parse PDF. Please try copying and pasting your content instead.' },
      { status: 500 }
    )
  } finally {
    // Clean up parser resources
    if (parser) {
      try {
        await parser.destroy()
      } catch {
        // Ignore cleanup errors
      }
    }
  }
}
