/**
 * Learning Module Seeding Script
 *
 * This script demonstrates how to create learning modules in the database.
 * Run with: npx tsx prisma/seed-learning-modules.ts
 *
 * IMPORTANT: Make sure you have an admin user in the database first!
 */

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding learning modules...')

  // Get or create admin user (you'll need to update this with your actual admin user ID)
  const adminUser = await prisma.user.findFirst({
    where: { role: 'ADMIN' },
  })

  if (!adminUser) {
    console.error('❌ No admin user found. Please create an admin user first.')
    return
  }

  // Get or create a category for learning modules
  const learnCategory = await prisma.articleCategory.upsert({
    where: { slug: 'sustainability-education' },
    update: {},
    create: {
      name: 'Sustainability Education',
      slug: 'sustainability-education',
      description: 'Educational content about sustainability topics',
      icon: '📚',
    },
  })

  console.log('✅ Category created/found:', learnCategory.name)

  // Example 1: SMALL module (Quick Facts)
  const smallModule = await prisma.article.upsert({
    where: { slug: 'carbon-footprint-basics' },
    update: {},
    create: {
      title: 'Carbon Footprint Basics',
      slug: 'carbon-footprint-basics',
      excerpt: 'Quick facts about carbon footprints and how to reduce them',
      content: `
        <div class="space-y-4">
          <h3 class="text-xl font-bold">What is a Carbon Footprint?</h3>
          <p>Your carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) generated by your actions.</p>

          <h3 class="text-xl font-bold">Quick Facts:</h3>
          <ul class="list-disc pl-6 space-y-2">
            <li><strong>Average US carbon footprint:</strong> 16 tons/year per person</li>
            <li><strong>Global average:</strong> 4 tons/year per person</li>
            <li><strong>Target to combat climate change:</strong> Under 2 tons/year</li>
          </ul>

          <h3 class="text-xl font-bold">Top 3 Ways to Reduce Your Footprint:</h3>
          <ol class="list-decimal pl-6 space-y-2">
            <li>Switch to renewable energy sources</li>
            <li>Reduce meat consumption (especially beef)</li>
            <li>Use public transportation or electric vehicles</li>
          </ol>

          <div class="bg-green-50 dark:bg-green-950 p-4 rounded-lg mt-4">
            <p class="font-bold">💡 Did you know?</p>
            <p>One transatlantic flight generates about 2 tons of CO₂ - equivalent to half the average person's annual footprint!</p>
          </div>
        </div>
      `,
      coverImage: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b6',
      status: 'PUBLISHED',
      publishedAt: new Date(),
      authorId: adminUser.id,
      categoryId: learnCategory.id,

      // Learning Module Fields
      moduleType: 'SMALL',
      estimatedTime: 5,
      difficulty: 'Beginner',
      readTime: 5,
    },
  })

  console.log('✅ Small module created:', smallModule.title)

  // Example 2: LARGE module (Multi-tab with Quiz)
  const largeModule = await prisma.article.upsert({
    where: { slug: 'renewable-energy-fundamentals' },
    update: {},
    create: {
      title: 'Renewable Energy Fundamentals',
      slug: 'renewable-energy-fundamentals',
      excerpt: 'Master the basics of renewable energy sources and their impact',
      content: 'This is a multi-section learning module. See tabs below.',
      coverImage: 'https://images.unsplash.com/photo-1509391366360-2e959784a276',
      status: 'PUBLISHED',
      publishedAt: new Date(),
      authorId: adminUser.id,
      categoryId: learnCategory.id,

      // Learning Module Fields
      moduleType: 'LARGE',
      estimatedTime: 20,
      difficulty: 'Intermediate',
      readTime: 20,

      // Module tabs (sections)
      moduleTabs: [
        {
          title: 'Introduction to Renewable Energy',
          content: `
            <h3 class="text-xl font-bold mb-4">What is Renewable Energy?</h3>
            <p class="mb-4">Renewable energy comes from natural sources that are constantly replenished. Unlike fossil fuels, these energy sources won't run out and produce little to no greenhouse gas emissions.</p>

            <h4 class="text-lg font-bold mb-2">Main Types:</h4>
            <ul class="list-disc pl-6 space-y-2">
              <li><strong>Solar:</strong> Energy from the sun</li>
              <li><strong>Wind:</strong> Energy from wind turbines</li>
              <li><strong>Hydro:</strong> Energy from moving water</li>
              <li><strong>Geothermal:</strong> Energy from Earth's heat</li>
              <li><strong>Biomass:</strong> Energy from organic materials</li>
            </ul>

            <div class="bg-blue-50 dark:bg-blue-950 p-4 rounded-lg mt-4">
              <p class="font-bold">📊 Global Impact</p>
              <p>Renewable energy accounted for 29.9% of global electricity generation in 2023, up from 19% in 2011.</p>
            </div>
          `
        },
        {
          title: 'Solar Power Deep Dive',
          content: `
            <h3 class="text-xl font-bold mb-4">Solar Energy</h3>
            <p class="mb-4">Solar photovoltaic (PV) technology converts sunlight directly into electricity. It's the fastest-growing renewable energy source globally.</p>

            <h4 class="text-lg font-bold mb-2">Key Statistics (2023):</h4>
            <ul class="list-disc pl-6 space-y-2">
              <li>444 GW of new solar capacity added worldwide</li>
              <li>89% cost decline since 2010</li>
              <li>Now the cheapest source of electricity in most regions</li>
              <li>Residential solar payback: 6-8 years average</li>
            </ul>

            <h4 class="text-lg font-bold mb-2 mt-4">How It Works:</h4>
            <p>Solar panels contain photovoltaic cells that absorb photons from sunlight. This energy knocks electrons loose, creating an electric current that can be captured and used.</p>
          `
        },
        {
          title: 'Wind Energy',
          content: `
            <h3 class="text-xl font-bold mb-4">Wind Power</h3>
            <p class="mb-4">Wind turbines convert the kinetic energy in wind into mechanical power, which can then be converted into electricity.</p>

            <h4 class="text-lg font-bold mb-2">Types of Wind Energy:</h4>
            <ul class="list-disc pl-6 space-y-2">
              <li><strong>Onshore wind:</strong> Turbines on land, most common and cost-effective</li>
              <li><strong>Offshore wind:</strong> Turbines in ocean, stronger and more consistent winds</li>
              <li><strong>Distributed wind:</strong> Small turbines for homes/farms</li>
            </ul>

            <div class="bg-green-50 dark:bg-green-950 p-4 rounded-lg mt-4">
              <p class="font-bold">🌬️ Fun Fact</p>
              <p>A single modern wind turbine can power about 1,500 homes per year!</p>
            </div>
          `
        },
        {
          title: 'Benefits & Challenges',
          content: `
            <h3 class="text-xl font-bold mb-4">Why Renewable Energy Matters</h3>

            <h4 class="text-lg font-bold mb-2 text-green-600">Benefits:</h4>
            <ul class="list-disc pl-6 space-y-2 mb-4">
              <li>Zero or near-zero greenhouse gas emissions</li>
              <li>Inexhaustible energy sources</li>
              <li>Lower air pollution and health benefits</li>
              <li>Job creation (renewable energy employs millions globally)</li>
              <li>Energy independence and security</li>
            </ul>

            <h4 class="text-lg font-bold mb-2 text-orange-600">Challenges:</h4>
            <ul class="list-disc pl-6 space-y-2">
              <li>Intermittency (solar doesn't work at night, wind isn't constant)</li>
              <li>Energy storage needed for reliability</li>
              <li>Higher upfront costs (though decreasing rapidly)</li>
              <li>Grid infrastructure upgrades required</li>
              <li>Geographic limitations for some sources</li>
            </ul>
          `
        },
        {
          title: 'Taking Action',
          content: `
            <h3 class="text-xl font-bold mb-4">How You Can Support Renewable Energy</h3>

            <h4 class="text-lg font-bold mb-2">Individual Actions:</h4>
            <ol class="list-decimal pl-6 space-y-2 mb-4">
              <li><strong>Install solar panels:</strong> If you own property, consider rooftop solar</li>
              <li><strong>Choose green energy plans:</strong> Many utilities offer renewable energy options</li>
              <li><strong>Support renewable energy policies:</strong> Vote and advocate for clean energy</li>
              <li><strong>Invest in green energy:</strong> Consider renewable energy stocks or funds</li>
              <li><strong>Reduce overall energy use:</strong> Efficiency is the cheapest form of energy</li>
            </ol>

            <div class="bg-purple-50 dark:bg-purple-950 p-4 rounded-lg">
              <p class="font-bold">🎯 Your Next Step</p>
              <p>Calculate your home's solar potential using Google's Project Sunroof or similar tools!</p>
            </div>
          `
        }
      ],

      // Quiz questions (5 questions, perfect score required)
      quizQuestions: [
        {
          question: 'What percentage of global electricity came from renewable energy in 2023?',
          type: 'multiple_choice',
          options: ['19%', '24.5%', '29.9%', '35%'],
          correctAnswer: '29.9%'
        },
        {
          question: 'Which renewable energy source is the fastest-growing globally?',
          type: 'multiple_choice',
          options: ['Wind', 'Solar', 'Hydro', 'Geothermal'],
          correctAnswer: 'Solar'
        },
        {
          question: 'Solar panel costs have declined by what percentage since 2010?',
          type: 'multiple_choice',
          options: ['45%', '67%', '89%', '92%'],
          correctAnswer: '89%'
        },
        {
          question: 'True or False: Offshore wind turbines generally have stronger and more consistent winds than onshore turbines.',
          type: 'true_false',
          options: ['True', 'False'],
          correctAnswer: 'True'
        },
        {
          question: 'Approximately how many homes can a single modern wind turbine power per year?',
          type: 'multiple_choice',
          options: ['500 homes', '1,000 homes', '1,500 homes', '2,000 homes'],
          correctAnswer: '1,500 homes'
        }
      ]
    },
  })

  console.log('✅ Large module created:', largeModule.title)

  console.log('\n🎉 Seeding complete!')
  console.log('\nCreated modules:')
  console.log('  1. Small module:', smallModule.title, `(${smallModule.slug})`)
  console.log('  2. Large module:', largeModule.title, `(${largeModule.slug})`)
  console.log('\n📝 To create more modules, follow these examples in your database or admin interface!')
}

main()
  .catch((e) => {
    console.error('❌ Error seeding modules:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
