import type { ArchitecturalElement } from '../../types';

export const FLYING_BUTTRESS: ArchitecturalElement = {
  id: 'flying-buttress',
  slug: 'flying-buttress',
  name: 'Flying Buttress',
  alternativeNames: ['Arc-boutant', 'Arch Buttress', 'External Arch Support'],
  pronunciation: {
    phonetic: 'FLY-ing BUH-tris',
    language: 'English/French',
  },
  etymology: {
    origin: 'French',
    meaning: 'Flying support arch',
    rootWord: 'arc-boutant (supporting arch)',
  },
  category: 'ROOF',
  subcategory: 'structural_support',
  periods: ['gothic', 'gothic-revival'],
  regions: ['NORTHERN_EUROPE', 'GLOBAL'],

  images: {
    primary: '/images/architecture/elements/flying-buttress-primary.jpg',
    gallery: [
      '/images/architecture/elements/flying-buttress-notre-dame.jpg',
      '/images/architecture/elements/flying-buttress-amiens.jpg',
    ],
    diagram: '/images/architecture/diagrams/flying-buttress-forces.svg',
  },

  description: {
    ELEMENTARY: 'Flying buttresses are stone arches that stick out from the side of a building like arms pushing against the wall. They help hold up tall Gothic cathedrals, keeping the walls from falling outward! They look like the building is being hugged by stone arms.',
    MIDDLE_SCHOOL: 'A flying buttress is an arched exterior support that transfers the lateral thrust from a vaulted ceiling or roof to an outer support pier. These dramatic arching structures allowed Gothic cathedrals to build higher walls with larger windows by moving the structural support outside the building. The arch "flies" across space from the wall to a separate buttress pier.',
    HIGH_SCHOOL: 'The flying buttress is a structural element consisting of an inclined bar or arch of masonry carried on a half-arch that extends from the upper part of a wall to a pier some distance away. It counters the lateral thrust generated by high stone vaults, redirecting forces downward to external buttress piers. This innovation enabled Gothic architecture\'s characteristic tall, thin walls with extensive glazing. The flying buttress typically consists of a sloping strut (the flyer) supported by a half-arch, often with multiple tiers for taller buildings. Buttress piers are often topped with pinnacles that add stabilizing weight.',
    UNDERGRADUATE: 'The flying buttress represents a revolutionary structural solution that fundamentally transformed Gothic architecture. By externalizing structural support, flying buttresses resolved the primary challenge of high masonry vaults-lateral thrust pushing walls outward. The system works through a chain of force transmission: vault thrust pushes against the upper wall, the flying arch receives this thrust and redirects it to the external pier, which channels forces to the ground. This enabled unprecedented height-to-thickness ratios in walls, permitting large window openings filled with stained glass. The structural efficiency of the pointed arch, ribbed vault, and flying buttress formed an integrated system defining Gothic architecture. Early Gothic buildings concealed buttresses under roofs, while mature Gothic celebrated them as expressive external elements.',
    GRADUATE: 'The flying buttress embodies empirical structural understanding predating formal engineering analysis. Gothic masons developed sophisticated rules-of-thumb for buttress sizing and placement, though their theoretical understanding of force transmission differed from modern statics. Analysis reveals the flying buttress as part of a complete structural system including vault ribs concentrating loads, pier clusters receiving these loads, and external buttressing resisting horizontal components. The element\'s evolution shows progressive refinement: early attempts with hidden buttresses, experimentation with double-tier systems for tall naves, optimization of arch profiles, and addition of pinnacles providing downward force improving stability. The flying buttress\'s aesthetic dimension-creating dynamic external rhythms and expressing structural forces-represents Gothic architecture\'s distinctive approach to tectonic honesty.',
    PHD: 'The flying buttress constitutes a crucial case study in pre-modern structural innovation and the relationship between empirical practice and theoretical understanding. Scholarly research employs multiple approaches: structural analysis using finite element modeling to understand force flow and assess historical designs, building archaeology documenting construction sequences and modifications, historical research examining design transmission through workshop practices, and theoretical studies analyzing Gothic structural thinking. Recent work challenges narratives of purely functional development, revealing aesthetic and symbolic dimensions-buttresses as manifestations of divine support, sculptural opportunities, and demonstrations of technical prowess. Conservation research addresses buttress deterioration including stone decay, structural movement, and iron clamp corrosion, developing intervention strategies balancing structural necessity with heritage values. Contemporary debates engage questions of appropriate reconstruction following disasters (Notre-Dame fire) and the element\'s potential in new construction using traditional or innovative materials.',
  },

  history: {
    ELEMENTARY: 'Gothic cathedral builders invented flying buttresses around 800 years ago to build churches taller than ever before. The first ones were hidden under roofs, but builders soon realized these amazing stone arches looked beautiful on the outside!',
    MIDDLE_SCHOOL: 'Flying buttresses emerged in 12th-century France as Gothic architects sought to build taller churches with larger windows. Early examples like Notre-Dame de Paris (1160s) initially hid buttresses, but builders soon recognized their structural value and aesthetic potential. By the 13th century, flying buttresses became a defining Gothic feature, reaching maximum elaboration in High Gothic cathedrals like Amiens and Reims.',
    HIGH_SCHOOL: 'The flying buttress evolved from earlier Romanesque external supports and hidden buttressing systems. Abbey churches like Vézelay and early Gothic buildings initially concealed buttresses under lean-to roofs. The first exposed flying buttresses appeared at Notre-Dame de Paris (added c. 1180s after construction began). Subsequent development at Chartres (1194-1220), Reims (1211-1275), and Amiens (1220-1270) refined the system, with Beauvais Cathedral (begun 1225) pushing structural limits so aggressively its vaults eventually collapsed. Gothic Revival architects of the 19th century revived flying buttresses, though often as decorative rather than structural elements.',
    UNDERGRADUATE: 'Flying buttress development traces from Romanesque precedents through Gothic experimentation to mature systematization. Early solutions including Norman thick-wall construction and Burgundian pointed arches addressed vault thrust differently. The critical innovation came in early Gothic Paris-Notre-Dame\'s original design lacked flying buttresses, which were added after construction when wall deflection became apparent. This retrofitting demonstrated the system\'s effectiveness, leading to deliberate incorporation at Chartres. Subsequent development optimized buttress placement, flyer angle (typically 45-60 degrees for maximum efficiency), pier proportions, and decorative elaboration. Regional variations emerged-French cathedrals with delicate multi-tiered buttresses, English cathedrals with heavier proportions, and Spanish and German adaptations. The system\'s decline followed Gothic\'s end, though structural principles informed later construction.',
    GRADUATE: 'The flying buttress\'s history reveals complex interactions between structural necessity, empirical development, and aesthetic intention. Recent scholarship challenges linear progress narratives, showing how builders developed sophisticated understanding through building experience rather than theoretical analysis. Archaeological evidence reveals experimentation-buildings with multiple construction campaigns show evolving buttress strategies as builders responded to structural behavior. The element\'s structural optimization involved multiple variables: flyer angle affecting force transmission efficiency, buttress pier mass providing necessary resistance, pinnacle weight increasing stability margins, and strut thickness balancing weight against strength. Aesthetic development shows conscious sculptural treatment transforming functional elements into Gothic architecture\'s defining visual characteristic. The flying buttress\'s reception varied-19th-century rationalists celebrated its functional honesty while others criticized it as structural exhibitionism.',
    PHD: 'Scholarly engagement with flying buttress history employs interdisciplinary methodologies combining architectural history, structural engineering, building archaeology, and materials science. Research addresses fundamental questions about Gothic builders\' structural knowledge-the extent to which they understood force diagrams, the role of geometry versus calculation, and knowledge transmission mechanisms through workshops. Computational analysis of existing structures reveals safety factors (often 2-3x), indicating conservative design despite dramatic appearance. Studies of structural failures (Beauvais, Troyes) inform understanding of design limits. Archaeological investigation documents construction techniques including formwork systems and scaffolding. Recent work examines iron reinforcement use in Gothic construction, revealing earlier adoption than previously recognized. Conservation research develops assessment protocols for buttress stability and deterioration, addressing challenges including differential settlement, stone decay, and climate change impacts on masonry structures.',
  },

  characteristics: [
    'Arched external support structure',
    'Transfers lateral thrust from walls/vaults',
    'Consists of flyer, arch, and buttress pier',
    'Often multi-tiered for tall buildings',
    'Typically topped with pinnacles',
    'Enables thin walls and large windows',
  ],

  famousExamples: [
    { name: 'Notre-Dame de Paris', location: 'Paris, France', year: 'c. 1180s (added)', description: 'Early flying buttresses, double-tiered' },
    { name: 'Chartres Cathedral', location: 'Chartres, France', year: '1194-1220', description: 'Refined High Gothic buttress system' },
    { name: 'Reims Cathedral', location: 'Reims, France', year: '1211-1275', description: 'Elaborately decorated buttresses' },
    { name: 'Amiens Cathedral', location: 'Amiens, France', year: '1220-1270', description: 'Tallest Gothic nave with sophisticated buttressing' },
    { name: 'Cologne Cathedral', location: 'Cologne, Germany', year: '1248-1880', description: 'German Gothic buttress interpretation' },
  ],

  confusionPairs: [
    {
      elementId: 'buttress',
      reason: 'Both provide external wall support',
      distinction: 'Buttress is a solid pier against the wall; flying buttress is an arched connection between wall and separate pier',
    },
    {
      elementId: 'arch',
      reason: 'Flying buttress uses arch form',
      distinction: 'Arch spans openings; flying buttress transfers lateral forces from wall to external support',
    },
  ],

  searchTags: ['gothic', 'arch', 'support', 'cathedral', 'structural', 'vault', 'buttress', 'pier', 'medieval', 'french'],

  arMetadata: {
    modelPath: '/models/architecture/flying-buttress.glb',
    scale: 2.0,
    rotatable: true,
    annotations: [
      { label: 'Pinnacle', position: { x: 0.5, y: 1.0, z: 0 } },
      { label: 'Buttress Pier', position: { x: 0.5, y: 0.5, z: 0 } },
      { label: 'Flying Arch (Flyer)', position: { x: 0.25, y: 0.7, z: 0 } },
      { label: 'Wall Connection', position: { x: 0, y: 0.8, z: 0 } },
    ],
  },

  difficultyScore: 4,
  dateAdded: new Date('2024-01-01'),
  lastUpdated: new Date('2024-01-01'),
};
